In [6]:
#importing the necessary libraries
import numpy 
import cv2
import os 
import pickle
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

In [7]:
#Loading in the cnn
net = cv2.dnn.readNetFromCaffe("./bvlc_alexnet.prototxt", "./bvlc_alexnet.caffemodel")

In [8]:
# Inspecting the cnn's architecture
layer_names = net.getLayerNames()
print(layer_names)

['conv1', 'relu1', 'norm1', 'pool1', 'conv2', 'relu2', 'norm2', 'pool2', 'conv3', 'relu3', 'conv4', 'relu4', 'conv5', 'relu5', 'pool5', 'fc6', 'relu6', 'drop6', 'fc7', 'relu7', 'drop7', 'fc8', 'prob']


In [9]:
def extract_feature(filename, foldername):
    print(filename)
    image = os.path.join('JPEGImages', foldername, filename)
    img = cv2.imread(image)
    #resizing and normailizing the image data to reach the desired state for the cnn
    # (1, 3, 224, 224)
    resized = cv2.resize(img,(224, 224), interpolation = cv2.INTER_CUBIC)
    blob = cv2.dnn.blobFromImage(resized, 1, (224, 224), (104, 117, 123))
    net.setInput(blob)

    # To get the feature representations of the training and test images, 
    # use activations on the fully connected layer 'fc7'
    features = net.forward("fc7")
    return features

In [10]:
#creating the necessary directory strings
cwd = os.getcwd()
imfold = os.path.join(cwd,"JPEGImages")
#ignoring the .ds_store files in the JPEGImages folder
dirlist = os.listdir(imfold)[1:]

In [11]:
#in this cell I create the extracted feature vectors for each class separately to help generate the y data later on

for folder in dirlist:
    extracted = []
    #creating a list of the image names present in the current folder
    currdir = os.path.join(imfold, folder)
    imlist = os.listdir(currdir)
    #skipping the .ds_store file and the extracted if re-extracting features
    for file in imlist:
        if file == "extracted.txt" or file == ".DS_Store":
            continue
        extracted.append(extract_feature(file, currdir))
    
    extracted = numpy.array(extracted)
    sh = extracted.shape
    extracted = extracted.reshape((sh[0], sh[2]))
    #checking the size of each folder's extracted vectors for imbalances in the data
    print(extracted.shape)
    
    numpy.savetxt(X=extracted, fname=os.path.join(currdir,"extracted.txt"))

antelope_10001.jpg
antelope_10002.jpg
antelope_10003.jpg
antelope_10004.jpg
antelope_10005.jpg
antelope_10006.jpg
antelope_10007.jpg
antelope_10008.jpg
antelope_10009.jpg
antelope_10010.jpg
antelope_10011.jpg
antelope_10012.jpg
antelope_10013.jpg
antelope_10014.jpg
antelope_10015.jpg
antelope_10016.jpg
antelope_10017.jpg
antelope_10018.jpg
antelope_10019.jpg
antelope_10020.jpg
antelope_10021.jpg
antelope_10022.jpg
antelope_10023.jpg
antelope_10024.jpg
antelope_10025.jpg
antelope_10026.jpg
antelope_10027.jpg
antelope_10028.jpg
antelope_10029.jpg
antelope_10030.jpg
antelope_10031.jpg
antelope_10032.jpg
antelope_10033.jpg
antelope_10034.jpg
antelope_10035.jpg
antelope_10036.jpg
antelope_10037.jpg
antelope_10038.jpg
antelope_10039.jpg
antelope_10040.jpg
antelope_10041.jpg
antelope_10042.jpg
antelope_10043.jpg
antelope_10044.jpg
antelope_10045.jpg
antelope_10046.jpg
antelope_10047.jpg
antelope_10048.jpg
antelope_10049.jpg
antelope_10050.jpg
antelope_10051.jpg
antelope_10052.jpg
antelope_100

beaver_10038.jpg
beaver_10039.jpg
beaver_10040.jpg
beaver_10041.jpg
beaver_10042.jpg
beaver_10043.jpg
beaver_10044.jpg
beaver_10045.jpg
beaver_10046.jpg
beaver_10047.jpg
beaver_10048.jpg
beaver_10049.jpg
beaver_10050.jpg
beaver_10051.jpg
beaver_10052.jpg
beaver_10053.jpg
beaver_10054.jpg
beaver_10055.jpg
beaver_10056.jpg
beaver_10057.jpg
beaver_10058.jpg
beaver_10059.jpg
beaver_10060.jpg
beaver_10061.jpg
beaver_10062.jpg
beaver_10063.jpg
beaver_10064.jpg
beaver_10065.jpg
beaver_10066.jpg
beaver_10067.jpg
beaver_10068.jpg
beaver_10069.jpg
beaver_10070.jpg
beaver_10071.jpg
beaver_10072.jpg
beaver_10073.jpg
beaver_10074.jpg
beaver_10075.jpg
beaver_10076.jpg
beaver_10077.jpg
beaver_10078.jpg
beaver_10079.jpg
beaver_10080.jpg
beaver_10081.jpg
beaver_10082.jpg
beaver_10083.jpg
beaver_10084.jpg
beaver_10085.jpg
beaver_10086.jpg
beaver_10087.jpg
beaver_10088.jpg
beaver_10089.jpg
beaver_10090.jpg
beaver_10091.jpg
beaver_10092.jpg
beaver_10093.jpg
beaver_10094.jpg
beaver_10095.jpg
beaver_10096.j

bobcat_10204.jpg
bobcat_10205.jpg
bobcat_10206.jpg
bobcat_10207.jpg
bobcat_10208.jpg
bobcat_10209.jpg
bobcat_10210.jpg
bobcat_10211.jpg
bobcat_10212.jpg
bobcat_10213.jpg
bobcat_10214.jpg
bobcat_10215.jpg
bobcat_10216.jpg
bobcat_10217.jpg
bobcat_10218.jpg
bobcat_10219.jpg
bobcat_10220.jpg
bobcat_10221.jpg
bobcat_10222.jpg
bobcat_10223.jpg
bobcat_10224.jpg
bobcat_10225.jpg
bobcat_10226.jpg
bobcat_10227.jpg
bobcat_10228.jpg
bobcat_10229.jpg
bobcat_10230.jpg
bobcat_10231.jpg
bobcat_10232.jpg
bobcat_10233.jpg
bobcat_10234.jpg
bobcat_10235.jpg
bobcat_10236.jpg
bobcat_10237.jpg
bobcat_10238.jpg
bobcat_10239.jpg
bobcat_10240.jpg
bobcat_10241.jpg
bobcat_10242.jpg
bobcat_10243.jpg
bobcat_10244.jpg
bobcat_10245.jpg
bobcat_10246.jpg
bobcat_10247.jpg
bobcat_10248.jpg
bobcat_10249.jpg
bobcat_10250.jpg
bobcat_10251.jpg
bobcat_10252.jpg
bobcat_10253.jpg
bobcat_10254.jpg
bobcat_10255.jpg
bobcat_10256.jpg
bobcat_10257.jpg
bobcat_10258.jpg
bobcat_10259.jpg
bobcat_10260.jpg
bobcat_10261.jpg
bobcat_10262.j

buffalo_10054.jpg
buffalo_10055.jpg
buffalo_10056.jpg
buffalo_10057.jpg
buffalo_10058.jpg
buffalo_10059.jpg
buffalo_10060.jpg
buffalo_10061.jpg
buffalo_10062.jpg
buffalo_10063.jpg
buffalo_10064.jpg
buffalo_10065.jpg
buffalo_10066.jpg
buffalo_10067.jpg
buffalo_10068.jpg
buffalo_10069.jpg
buffalo_10070.jpg
buffalo_10071.jpg
buffalo_10072.jpg
buffalo_10073.jpg
buffalo_10074.jpg
buffalo_10075.jpg
buffalo_10076.jpg
buffalo_10077.jpg
buffalo_10078.jpg
buffalo_10079.jpg
buffalo_10080.jpg
buffalo_10081.jpg
buffalo_10082.jpg
buffalo_10083.jpg
buffalo_10084.jpg
buffalo_10085.jpg
buffalo_10086.jpg
buffalo_10087.jpg
buffalo_10088.jpg
buffalo_10089.jpg
buffalo_10090.jpg
buffalo_10091.jpg
buffalo_10092.jpg
buffalo_10093.jpg
buffalo_10094.jpg
buffalo_10095.jpg
buffalo_10096.jpg
buffalo_10097.jpg
buffalo_10098.jpg
buffalo_10099.jpg
buffalo_10100.jpg
buffalo_10101.jpg
buffalo_10102.jpg
buffalo_10103.jpg
buffalo_10104.jpg
buffalo_10105.jpg
buffalo_10106.jpg
buffalo_10107.jpg
buffalo_10108.jpg
buffalo_10

chihuahua_10099.jpg
chihuahua_10100.jpg
chihuahua_10101.jpg
chihuahua_10102.jpg
chihuahua_10103.jpg
chihuahua_10104.jpg
chihuahua_10105.jpg
chihuahua_10106.jpg
chihuahua_10107.jpg
chihuahua_10108.jpg
chihuahua_10109.jpg
chihuahua_10110.jpg
chihuahua_10111.jpg
chihuahua_10112.jpg
chihuahua_10113.jpg
chihuahua_10114.jpg
chihuahua_10115.jpg
chihuahua_10116.jpg
chihuahua_10117.jpg
chihuahua_10118.jpg
chihuahua_10119.jpg
chihuahua_10120.jpg
chihuahua_10121.jpg
chihuahua_10122.jpg
chihuahua_10123.jpg
chihuahua_10124.jpg
chihuahua_10125.jpg
chihuahua_10126.jpg
chihuahua_10127.jpg
chihuahua_10128.jpg
chihuahua_10129.jpg
chihuahua_10130.jpg
chihuahua_10131.jpg
chihuahua_10132.jpg
chihuahua_10133.jpg
chihuahua_10134.jpg
chihuahua_10135.jpg
chihuahua_10136.jpg
chihuahua_10137.jpg
chihuahua_10138.jpg
chihuahua_10139.jpg
chihuahua_10140.jpg
chihuahua_10141.jpg
chihuahua_10142.jpg
chihuahua_10143.jpg
chihuahua_10144.jpg
chihuahua_10145.jpg
chihuahua_10146.jpg
chihuahua_10147.jpg
chihuahua_10148.jpg


chimpanzee_10152.jpg
chimpanzee_10153.jpg
chimpanzee_10154.jpg
chimpanzee_10155.jpg
chimpanzee_10156.jpg
chimpanzee_10157.jpg
chimpanzee_10158.jpg
chimpanzee_10159.jpg
chimpanzee_10160.jpg
chimpanzee_10161.jpg
chimpanzee_10162.jpg
chimpanzee_10163.jpg
chimpanzee_10164.jpg
chimpanzee_10165.jpg
chimpanzee_10166.jpg
chimpanzee_10167.jpg
chimpanzee_10168.jpg
chimpanzee_10169.jpg
chimpanzee_10170.jpg
chimpanzee_10171.jpg
chimpanzee_10172.jpg
chimpanzee_10173.jpg
chimpanzee_10174.jpg
chimpanzee_10175.jpg
chimpanzee_10176.jpg
chimpanzee_10177.jpg
chimpanzee_10178.jpg
chimpanzee_10179.jpg
chimpanzee_10180.jpg
chimpanzee_10181.jpg
chimpanzee_10182.jpg
chimpanzee_10183.jpg
chimpanzee_10184.jpg
chimpanzee_10185.jpg
chimpanzee_10186.jpg
chimpanzee_10187.jpg
chimpanzee_10188.jpg
chimpanzee_10189.jpg
chimpanzee_10190.jpg
chimpanzee_10191.jpg
chimpanzee_10192.jpg
chimpanzee_10193.jpg
chimpanzee_10194.jpg
chimpanzee_10195.jpg
chimpanzee_10196.jpg
chimpanzee_10197.jpg
chimpanzee_10198.jpg
chimpanzee_10

collie_10424.jpg
collie_10425.jpg
collie_10426.jpg
collie_10427.jpg
collie_10428.jpg
collie_10429.jpg
collie_10430.jpg
collie_10431.jpg
collie_10432.jpg
collie_10433.jpg
collie_10434.jpg
collie_10435.jpg
collie_10436.jpg
collie_10437.jpg
collie_10438.jpg
collie_10439.jpg
collie_10440.jpg
collie_10441.jpg
collie_10442.jpg
collie_10443.jpg
collie_10444.jpg
collie_10445.jpg
collie_10446.jpg
collie_10447.jpg
collie_10448.jpg
collie_10449.jpg
collie_10450.jpg
collie_10451.jpg
collie_10452.jpg
collie_10453.jpg
collie_10454.jpg
collie_10455.jpg
collie_10456.jpg
collie_10457.jpg
collie_10458.jpg
collie_10459.jpg
collie_10460.jpg
collie_10461.jpg
collie_10462.jpg
collie_10463.jpg
collie_10464.jpg
collie_10465.jpg
collie_10466.jpg
collie_10467.jpg
collie_10468.jpg
collie_10469.jpg
collie_10470.jpg
collie_10471.jpg
collie_10472.jpg
collie_10473.jpg
collie_10474.jpg
collie_10475.jpg
collie_10476.jpg
collie_10477.jpg
collie_10478.jpg
collie_10479.jpg
collie_10480.jpg
collie_10481.jpg
collie_10482.j

cow_10492.jpg
cow_10493.jpg
cow_10494.jpg
cow_10495.jpg
cow_10496.jpg
cow_10497.jpg
cow_10498.jpg
cow_10499.jpg
cow_10500.jpg
(500, 4096)
dalmatian_10001.jpg
dalmatian_10002.jpg
dalmatian_10003.jpg
dalmatian_10004.jpg
dalmatian_10005.jpg
dalmatian_10006.jpg
dalmatian_10007.jpg
dalmatian_10008.jpg
dalmatian_10009.jpg
dalmatian_10010.jpg
dalmatian_10011.jpg
dalmatian_10012.jpg
dalmatian_10013.jpg
dalmatian_10014.jpg
dalmatian_10015.jpg
dalmatian_10016.jpg
dalmatian_10017.jpg
dalmatian_10018.jpg
dalmatian_10019.jpg
dalmatian_10020.jpg
dalmatian_10021.jpg
dalmatian_10022.jpg
dalmatian_10023.jpg
dalmatian_10024.jpg
dalmatian_10025.jpg
dalmatian_10026.jpg
dalmatian_10027.jpg
dalmatian_10028.jpg
dalmatian_10029.jpg
dalmatian_10030.jpg
dalmatian_10031.jpg
dalmatian_10032.jpg
dalmatian_10033.jpg
dalmatian_10034.jpg
dalmatian_10035.jpg
dalmatian_10036.jpg
dalmatian_10037.jpg
dalmatian_10038.jpg
dalmatian_10039.jpg
dalmatian_10040.jpg
dalmatian_10041.jpg
dalmatian_10042.jpg
dalmatian_10043.jpg
da

deer_10206.jpg
deer_10207.jpg
deer_10208.jpg
deer_10209.jpg
deer_10210.jpg
deer_10211.jpg
deer_10212.jpg
deer_10213.jpg
deer_10214.jpg
deer_10215.jpg
deer_10216.jpg
deer_10217.jpg
deer_10218.jpg
deer_10219.jpg
deer_10220.jpg
deer_10221.jpg
deer_10222.jpg
deer_10223.jpg
deer_10224.jpg
deer_10225.jpg
deer_10226.jpg
deer_10227.jpg
deer_10228.jpg
deer_10229.jpg
deer_10230.jpg
deer_10231.jpg
deer_10232.jpg
deer_10233.jpg
deer_10234.jpg
deer_10235.jpg
deer_10236.jpg
deer_10237.jpg
deer_10238.jpg
deer_10239.jpg
deer_10240.jpg
deer_10241.jpg
deer_10242.jpg
deer_10243.jpg
deer_10244.jpg
deer_10245.jpg
deer_10246.jpg
deer_10247.jpg
deer_10248.jpg
deer_10249.jpg
deer_10250.jpg
deer_10251.jpg
deer_10252.jpg
deer_10253.jpg
deer_10254.jpg
deer_10255.jpg
deer_10256.jpg
deer_10257.jpg
deer_10258.jpg
deer_10259.jpg
deer_10260.jpg
deer_10261.jpg
deer_10262.jpg
deer_10263.jpg
deer_10264.jpg
deer_10265.jpg
deer_10266.jpg
deer_10267.jpg
deer_10268.jpg
deer_10269.jpg
deer_10270.jpg
deer_10271.jpg
deer_10272

dolphin_10213.jpg
dolphin_10214.jpg
dolphin_10215.jpg
dolphin_10216.jpg
dolphin_10217.jpg
dolphin_10218.jpg
dolphin_10219.jpg
dolphin_10220.jpg
dolphin_10221.jpg
dolphin_10222.jpg
dolphin_10223.jpg
dolphin_10224.jpg
dolphin_10225.jpg
dolphin_10226.jpg
dolphin_10227.jpg
dolphin_10228.jpg
dolphin_10229.jpg
dolphin_10230.jpg
dolphin_10231.jpg
dolphin_10232.jpg
dolphin_10233.jpg
dolphin_10234.jpg
dolphin_10235.jpg
dolphin_10236.jpg
dolphin_10237.jpg
dolphin_10238.jpg
dolphin_10239.jpg
dolphin_10240.jpg
dolphin_10241.jpg
dolphin_10242.jpg
dolphin_10243.jpg
dolphin_10244.jpg
dolphin_10245.jpg
dolphin_10246.jpg
dolphin_10247.jpg
dolphin_10248.jpg
dolphin_10249.jpg
dolphin_10250.jpg
dolphin_10251.jpg
dolphin_10252.jpg
dolphin_10253.jpg
dolphin_10254.jpg
dolphin_10255.jpg
dolphin_10256.jpg
dolphin_10257.jpg
dolphin_10258.jpg
dolphin_10259.jpg
dolphin_10260.jpg
dolphin_10261.jpg
dolphin_10262.jpg
dolphin_10263.jpg
dolphin_10264.jpg
dolphin_10265.jpg
dolphin_10266.jpg
dolphin_10267.jpg
dolphin_10

elephant_10160.jpg
elephant_10161.jpg
elephant_10162.jpg
elephant_10163.jpg
elephant_10164.jpg
elephant_10165.jpg
elephant_10166.jpg
elephant_10167.jpg
elephant_10168.jpg
elephant_10169.jpg
elephant_10170.jpg
elephant_10171.jpg
elephant_10172.jpg
elephant_10173.jpg
elephant_10174.jpg
elephant_10175.jpg
elephant_10176.jpg
elephant_10177.jpg
elephant_10178.jpg
elephant_10179.jpg
elephant_10180.jpg
elephant_10181.jpg
elephant_10182.jpg
elephant_10183.jpg
elephant_10184.jpg
elephant_10185.jpg
elephant_10186.jpg
elephant_10187.jpg
elephant_10188.jpg
elephant_10189.jpg
elephant_10190.jpg
elephant_10191.jpg
elephant_10192.jpg
elephant_10193.jpg
elephant_10194.jpg
elephant_10195.jpg
elephant_10196.jpg
elephant_10197.jpg
elephant_10198.jpg
elephant_10199.jpg
elephant_10200.jpg
(200, 4096)
fox_10001.jpg
fox_10002.jpg
fox_10003.jpg
fox_10004.jpg
fox_10005.jpg
fox_10006.jpg
fox_10007.jpg
fox_10008.jpg
fox_10009.jpg
fox_10010.jpg
fox_10011.jpg
fox_10012.jpg
fox_10013.jpg
fox_10014.jpg
fox_10015.jpg

german+shepherd_10097.jpg
german+shepherd_10098.jpg
german+shepherd_10099.jpg
german+shepherd_10100.jpg
german+shepherd_10101.jpg
german+shepherd_10102.jpg
german+shepherd_10103.jpg
german+shepherd_10104.jpg
german+shepherd_10105.jpg
german+shepherd_10106.jpg
german+shepherd_10107.jpg
german+shepherd_10108.jpg
german+shepherd_10109.jpg
german+shepherd_10110.jpg
german+shepherd_10111.jpg
german+shepherd_10112.jpg
german+shepherd_10113.jpg
german+shepherd_10114.jpg
german+shepherd_10115.jpg
german+shepherd_10116.jpg
german+shepherd_10117.jpg
german+shepherd_10118.jpg
german+shepherd_10119.jpg
german+shepherd_10120.jpg
german+shepherd_10121.jpg
german+shepherd_10122.jpg
german+shepherd_10123.jpg
german+shepherd_10124.jpg
german+shepherd_10125.jpg
german+shepherd_10126.jpg
german+shepherd_10127.jpg
german+shepherd_10128.jpg
german+shepherd_10129.jpg
german+shepherd_10130.jpg
german+shepherd_10131.jpg
german+shepherd_10132.jpg
german+shepherd_10133.jpg
german+shepherd_10134.jpg
german+sheph

giraffe_10001.jpg
giraffe_10002.jpg
giraffe_10003.jpg
giraffe_10004.jpg
giraffe_10005.jpg
giraffe_10006.jpg
giraffe_10007.jpg
giraffe_10008.jpg
giraffe_10009.jpg
giraffe_10010.jpg
giraffe_10011.jpg
giraffe_10012.jpg
giraffe_10013.jpg
giraffe_10014.jpg
giraffe_10015.jpg
giraffe_10016.jpg
giraffe_10017.jpg
giraffe_10018.jpg
giraffe_10019.jpg
giraffe_10020.jpg
giraffe_10021.jpg
giraffe_10022.jpg
giraffe_10023.jpg
giraffe_10024.jpg
giraffe_10025.jpg
giraffe_10026.jpg
giraffe_10027.jpg
giraffe_10028.jpg
giraffe_10029.jpg
giraffe_10030.jpg
giraffe_10031.jpg
giraffe_10032.jpg
giraffe_10033.jpg
giraffe_10034.jpg
giraffe_10035.jpg
giraffe_10036.jpg
giraffe_10037.jpg
giraffe_10038.jpg
giraffe_10039.jpg
giraffe_10040.jpg
giraffe_10041.jpg
giraffe_10042.jpg
giraffe_10043.jpg
giraffe_10044.jpg
giraffe_10045.jpg
giraffe_10046.jpg
giraffe_10047.jpg
giraffe_10048.jpg
giraffe_10049.jpg
giraffe_10050.jpg
giraffe_10051.jpg
giraffe_10052.jpg
giraffe_10053.jpg
giraffe_10054.jpg
giraffe_10055.jpg
giraffe_10

gorilla_10156.jpg
gorilla_10157.jpg
gorilla_10158.jpg
gorilla_10159.jpg
gorilla_10160.jpg
gorilla_10161.jpg
gorilla_10162.jpg
gorilla_10163.jpg
gorilla_10164.jpg
gorilla_10165.jpg
gorilla_10166.jpg
gorilla_10167.jpg
gorilla_10168.jpg
gorilla_10169.jpg
gorilla_10170.jpg
gorilla_10171.jpg
gorilla_10172.jpg
gorilla_10173.jpg
gorilla_10174.jpg
gorilla_10175.jpg
gorilla_10176.jpg
gorilla_10177.jpg
gorilla_10178.jpg
gorilla_10179.jpg
gorilla_10180.jpg
gorilla_10181.jpg
gorilla_10182.jpg
gorilla_10183.jpg
gorilla_10184.jpg
gorilla_10185.jpg
gorilla_10186.jpg
gorilla_10187.jpg
gorilla_10188.jpg
gorilla_10189.jpg
gorilla_10190.jpg
gorilla_10191.jpg
gorilla_10192.jpg
gorilla_10193.jpg
gorilla_10194.jpg
gorilla_10195.jpg
gorilla_10196.jpg
gorilla_10197.jpg
gorilla_10198.jpg
gorilla_10199.jpg
gorilla_10200.jpg
gorilla_10201.jpg
gorilla_10202.jpg
gorilla_10203.jpg
gorilla_10204.jpg
gorilla_10205.jpg
gorilla_10206.jpg
gorilla_10207.jpg
gorilla_10208.jpg
gorilla_10209.jpg
gorilla_10210.jpg
gorilla_10

hamster_10108.jpg
hamster_10109.jpg
hamster_10110.jpg
hamster_10111.jpg
hamster_10112.jpg
hamster_10113.jpg
hamster_10114.jpg
hamster_10115.jpg
hamster_10116.jpg
hamster_10117.jpg
hamster_10118.jpg
hamster_10119.jpg
hamster_10120.jpg
hamster_10121.jpg
hamster_10122.jpg
hamster_10123.jpg
hamster_10124.jpg
hamster_10125.jpg
hamster_10126.jpg
hamster_10127.jpg
hamster_10128.jpg
hamster_10129.jpg
hamster_10130.jpg
hamster_10131.jpg
hamster_10132.jpg
hamster_10133.jpg
hamster_10134.jpg
hamster_10135.jpg
hamster_10136.jpg
hamster_10137.jpg
hamster_10138.jpg
hamster_10139.jpg
hamster_10140.jpg
hamster_10141.jpg
hamster_10142.jpg
hamster_10143.jpg
hamster_10144.jpg
hamster_10145.jpg
hamster_10146.jpg
hamster_10147.jpg
hamster_10148.jpg
hamster_10149.jpg
hamster_10150.jpg
hamster_10151.jpg
hamster_10152.jpg
hamster_10153.jpg
hamster_10154.jpg
hamster_10155.jpg
hamster_10156.jpg
hamster_10157.jpg
hamster_10158.jpg
hamster_10159.jpg
hamster_10160.jpg
hamster_10161.jpg
hamster_10162.jpg
hamster_10

hippopotamus_10209.jpg
hippopotamus_10210.jpg
hippopotamus_10211.jpg
hippopotamus_10212.jpg
hippopotamus_10213.jpg
hippopotamus_10214.jpg
hippopotamus_10215.jpg
hippopotamus_10216.jpg
hippopotamus_10217.jpg
hippopotamus_10218.jpg
hippopotamus_10219.jpg
hippopotamus_10220.jpg
hippopotamus_10221.jpg
hippopotamus_10222.jpg
hippopotamus_10223.jpg
hippopotamus_10224.jpg
hippopotamus_10225.jpg
hippopotamus_10226.jpg
hippopotamus_10227.jpg
hippopotamus_10228.jpg
hippopotamus_10229.jpg
hippopotamus_10230.jpg
hippopotamus_10231.jpg
hippopotamus_10232.jpg
hippopotamus_10233.jpg
hippopotamus_10234.jpg
hippopotamus_10235.jpg
hippopotamus_10236.jpg
hippopotamus_10237.jpg
hippopotamus_10238.jpg
hippopotamus_10239.jpg
hippopotamus_10240.jpg
hippopotamus_10241.jpg
hippopotamus_10242.jpg
hippopotamus_10243.jpg
hippopotamus_10244.jpg
hippopotamus_10245.jpg
hippopotamus_10246.jpg
hippopotamus_10247.jpg
hippopotamus_10248.jpg
hippopotamus_10249.jpg
hippopotamus_10250.jpg
hippopotamus_10251.jpg
hippopotamu

humpback+whale_10055.jpg
humpback+whale_10056.jpg
humpback+whale_10057.jpg
humpback+whale_10058.jpg
humpback+whale_10059.jpg
humpback+whale_10060.jpg
humpback+whale_10061.jpg
humpback+whale_10062.jpg
humpback+whale_10063.jpg
humpback+whale_10064.jpg
humpback+whale_10065.jpg
humpback+whale_10066.jpg
humpback+whale_10067.jpg
humpback+whale_10068.jpg
humpback+whale_10069.jpg
humpback+whale_10070.jpg
humpback+whale_10071.jpg
humpback+whale_10072.jpg
humpback+whale_10073.jpg
humpback+whale_10074.jpg
humpback+whale_10075.jpg
humpback+whale_10076.jpg
humpback+whale_10077.jpg
humpback+whale_10078.jpg
humpback+whale_10079.jpg
humpback+whale_10080.jpg
humpback+whale_10081.jpg
humpback+whale_10082.jpg
humpback+whale_10083.jpg
humpback+whale_10084.jpg
humpback+whale_10085.jpg
humpback+whale_10086.jpg
humpback+whale_10087.jpg
humpback+whale_10088.jpg
humpback+whale_10089.jpg
humpback+whale_10090.jpg
humpback+whale_10091.jpg
humpback+whale_10092.jpg
humpback+whale_10093.jpg
humpback+whale_10094.jpg


killer+whale_10091.jpg
killer+whale_10092.jpg
killer+whale_10093.jpg
killer+whale_10094.jpg
killer+whale_10095.jpg
killer+whale_10096.jpg
killer+whale_10097.jpg
killer+whale_10098.jpg
killer+whale_10099.jpg
killer+whale_10100.jpg
killer+whale_10101.jpg
killer+whale_10102.jpg
killer+whale_10103.jpg
killer+whale_10104.jpg
killer+whale_10105.jpg
killer+whale_10106.jpg
killer+whale_10107.jpg
killer+whale_10108.jpg
killer+whale_10109.jpg
killer+whale_10110.jpg
killer+whale_10111.jpg
killer+whale_10112.jpg
killer+whale_10113.jpg
killer+whale_10114.jpg
killer+whale_10115.jpg
killer+whale_10116.jpg
killer+whale_10117.jpg
killer+whale_10118.jpg
killer+whale_10119.jpg
killer+whale_10120.jpg
killer+whale_10121.jpg
killer+whale_10122.jpg
killer+whale_10123.jpg
killer+whale_10124.jpg
killer+whale_10125.jpg
killer+whale_10126.jpg
killer+whale_10127.jpg
killer+whale_10128.jpg
killer+whale_10129.jpg
killer+whale_10130.jpg
killer+whale_10131.jpg
killer+whale_10132.jpg
killer+whale_10133.jpg
killer+whal

lion_10215.jpg
lion_10216.jpg
lion_10217.jpg
lion_10218.jpg
lion_10219.jpg
lion_10220.jpg
lion_10221.jpg
lion_10222.jpg
lion_10223.jpg
lion_10224.jpg
lion_10225.jpg
lion_10226.jpg
lion_10227.jpg
lion_10228.jpg
lion_10229.jpg
lion_10230.jpg
lion_10231.jpg
lion_10232.jpg
lion_10233.jpg
lion_10234.jpg
lion_10235.jpg
lion_10236.jpg
lion_10237.jpg
lion_10238.jpg
lion_10239.jpg
lion_10240.jpg
lion_10241.jpg
lion_10242.jpg
lion_10243.jpg
lion_10244.jpg
lion_10245.jpg
lion_10246.jpg
lion_10247.jpg
lion_10248.jpg
lion_10249.jpg
lion_10250.jpg
lion_10251.jpg
lion_10252.jpg
lion_10253.jpg
lion_10254.jpg
lion_10255.jpg
lion_10256.jpg
lion_10257.jpg
lion_10258.jpg
lion_10259.jpg
lion_10260.jpg
lion_10261.jpg
lion_10262.jpg
lion_10263.jpg
lion_10264.jpg
lion_10265.jpg
lion_10266.jpg
lion_10267.jpg
lion_10268.jpg
lion_10269.jpg
lion_10270.jpg
lion_10271.jpg
lion_10272.jpg
lion_10273.jpg
lion_10274.jpg
lion_10275.jpg
lion_10276.jpg
lion_10277.jpg
lion_10278.jpg
lion_10279.jpg
lion_10280.jpg
lion_10281

moose_10153.jpg
moose_10154.jpg
moose_10155.jpg
moose_10156.jpg
moose_10157.jpg
moose_10158.jpg
moose_10159.jpg
moose_10160.jpg
moose_10161.jpg
moose_10162.jpg
moose_10163.jpg
moose_10164.jpg
moose_10165.jpg
moose_10166.jpg
moose_10167.jpg
moose_10168.jpg
moose_10169.jpg
moose_10170.jpg
moose_10171.jpg
moose_10172.jpg
moose_10173.jpg
moose_10174.jpg
moose_10175.jpg
moose_10176.jpg
moose_10177.jpg
moose_10178.jpg
moose_10179.jpg
moose_10180.jpg
moose_10181.jpg
moose_10182.jpg
moose_10183.jpg
moose_10184.jpg
moose_10185.jpg
moose_10186.jpg
moose_10187.jpg
moose_10188.jpg
moose_10189.jpg
moose_10190.jpg
moose_10191.jpg
moose_10192.jpg
moose_10193.jpg
moose_10194.jpg
moose_10195.jpg
moose_10196.jpg
moose_10197.jpg
moose_10198.jpg
moose_10199.jpg
moose_10200.jpg
moose_10201.jpg
moose_10202.jpg
moose_10203.jpg
moose_10204.jpg
moose_10205.jpg
moose_10206.jpg
moose_10207.jpg
moose_10208.jpg
moose_10209.jpg
moose_10210.jpg
moose_10211.jpg
moose_10212.jpg
moose_10213.jpg
moose_10214.jpg
moose_10

otter_10181.jpg
otter_10182.jpg
otter_10183.jpg
otter_10184.jpg
otter_10185.jpg
otter_10186.jpg
otter_10187.jpg
otter_10188.jpg
otter_10189.jpg
otter_10190.jpg
otter_10191.jpg
otter_10192.jpg
otter_10193.jpg
otter_10194.jpg
otter_10195.jpg
otter_10196.jpg
otter_10197.jpg
otter_10198.jpg
otter_10199.jpg
otter_10200.jpg
otter_10201.jpg
otter_10202.jpg
otter_10203.jpg
otter_10204.jpg
otter_10205.jpg
otter_10206.jpg
otter_10207.jpg
otter_10208.jpg
otter_10209.jpg
otter_10210.jpg
otter_10211.jpg
otter_10212.jpg
otter_10213.jpg
otter_10214.jpg
otter_10215.jpg
otter_10216.jpg
otter_10217.jpg
otter_10218.jpg
otter_10219.jpg
otter_10220.jpg
otter_10221.jpg
otter_10222.jpg
otter_10223.jpg
otter_10224.jpg
otter_10225.jpg
otter_10226.jpg
otter_10227.jpg
otter_10228.jpg
otter_10229.jpg
otter_10230.jpg
otter_10231.jpg
otter_10232.jpg
otter_10233.jpg
otter_10234.jpg
otter_10235.jpg
otter_10236.jpg
otter_10237.jpg
otter_10238.jpg
otter_10239.jpg
otter_10240.jpg
otter_10241.jpg
otter_10242.jpg
otter_10

persian+cat_10073.jpg
persian+cat_10074.jpg
persian+cat_10075.jpg
persian+cat_10076.jpg
persian+cat_10077.jpg
persian+cat_10078.jpg
persian+cat_10079.jpg
persian+cat_10080.jpg
persian+cat_10081.jpg
persian+cat_10082.jpg
persian+cat_10083.jpg
persian+cat_10084.jpg
persian+cat_10085.jpg
persian+cat_10086.jpg
persian+cat_10087.jpg
persian+cat_10088.jpg
persian+cat_10089.jpg
persian+cat_10090.jpg
persian+cat_10091.jpg
persian+cat_10092.jpg
persian+cat_10093.jpg
persian+cat_10094.jpg
persian+cat_10095.jpg
persian+cat_10096.jpg
persian+cat_10097.jpg
persian+cat_10098.jpg
persian+cat_10099.jpg
persian+cat_10100.jpg
persian+cat_10101.jpg
persian+cat_10102.jpg
persian+cat_10103.jpg
persian+cat_10104.jpg
persian+cat_10105.jpg
persian+cat_10106.jpg
persian+cat_10107.jpg
persian+cat_10108.jpg
persian+cat_10109.jpg
persian+cat_10110.jpg
persian+cat_10111.jpg
persian+cat_10112.jpg
persian+cat_10113.jpg
persian+cat_10114.jpg
persian+cat_10115.jpg
persian+cat_10116.jpg
persian+cat_10117.jpg
persian+ca

polar+bear_10092.jpg
polar+bear_10093.jpg
polar+bear_10094.jpg
polar+bear_10095.jpg
polar+bear_10096.jpg
polar+bear_10097.jpg
polar+bear_10098.jpg
polar+bear_10099.jpg
polar+bear_10100.jpg
polar+bear_10101.jpg
polar+bear_10102.jpg
polar+bear_10103.jpg
polar+bear_10104.jpg
polar+bear_10105.jpg
polar+bear_10106.jpg
polar+bear_10107.jpg
polar+bear_10108.jpg
polar+bear_10109.jpg
polar+bear_10110.jpg
polar+bear_10111.jpg
polar+bear_10112.jpg
polar+bear_10113.jpg
polar+bear_10114.jpg
polar+bear_10115.jpg
polar+bear_10116.jpg
polar+bear_10117.jpg
polar+bear_10118.jpg
polar+bear_10119.jpg
polar+bear_10120.jpg
polar+bear_10121.jpg
polar+bear_10122.jpg
polar+bear_10123.jpg
polar+bear_10124.jpg
polar+bear_10125.jpg
polar+bear_10126.jpg
polar+bear_10127.jpg
polar+bear_10128.jpg
polar+bear_10129.jpg
polar+bear_10130.jpg
polar+bear_10131.jpg
polar+bear_10132.jpg
polar+bear_10133.jpg
polar+bear_10134.jpg
polar+bear_10135.jpg
polar+bear_10136.jpg
polar+bear_10137.jpg
polar+bear_10138.jpg
polar+bear_10

polar+bear_10483.jpg
polar+bear_10484.jpg
polar+bear_10485.jpg
polar+bear_10486.jpg
polar+bear_10487.jpg
polar+bear_10488.jpg
polar+bear_10489.jpg
polar+bear_10490.jpg
polar+bear_10491.jpg
polar+bear_10492.jpg
polar+bear_10493.jpg
polar+bear_10494.jpg
polar+bear_10495.jpg
polar+bear_10496.jpg
polar+bear_10497.jpg
polar+bear_10498.jpg
polar+bear_10499.jpg
polar+bear_10500.jpg
(500, 4096)
rabbit_10001.jpg
rabbit_10002.jpg
rabbit_10003.jpg
rabbit_10004.jpg
rabbit_10005.jpg
rabbit_10006.jpg
rabbit_10007.jpg
rabbit_10008.jpg
rabbit_10009.jpg
rabbit_10010.jpg
rabbit_10011.jpg
rabbit_10012.jpg
rabbit_10013.jpg
rabbit_10014.jpg
rabbit_10015.jpg
rabbit_10016.jpg
rabbit_10017.jpg
rabbit_10018.jpg
rabbit_10019.jpg
rabbit_10020.jpg
rabbit_10021.jpg
rabbit_10022.jpg
rabbit_10023.jpg
rabbit_10024.jpg
rabbit_10025.jpg
rabbit_10026.jpg
rabbit_10027.jpg
rabbit_10028.jpg
rabbit_10029.jpg
rabbit_10030.jpg
rabbit_10031.jpg
rabbit_10032.jpg
rabbit_10033.jpg
rabbit_10034.jpg
rabbit_10035.jpg
rabbit_10036.jp

raccoon_10151.jpg
raccoon_10152.jpg
raccoon_10153.jpg
raccoon_10154.jpg
raccoon_10155.jpg
raccoon_10156.jpg
raccoon_10157.jpg
raccoon_10158.jpg
raccoon_10159.jpg
raccoon_10160.jpg
raccoon_10161.jpg
raccoon_10162.jpg
raccoon_10163.jpg
raccoon_10164.jpg
raccoon_10165.jpg
raccoon_10166.jpg
raccoon_10167.jpg
raccoon_10168.jpg
raccoon_10169.jpg
raccoon_10170.jpg
raccoon_10171.jpg
raccoon_10172.jpg
raccoon_10173.jpg
raccoon_10174.jpg
raccoon_10175.jpg
raccoon_10176.jpg
raccoon_10177.jpg
raccoon_10178.jpg
raccoon_10179.jpg
raccoon_10180.jpg
raccoon_10181.jpg
raccoon_10182.jpg
raccoon_10183.jpg
raccoon_10184.jpg
raccoon_10185.jpg
raccoon_10186.jpg
raccoon_10187.jpg
raccoon_10188.jpg
raccoon_10189.jpg
raccoon_10190.jpg
raccoon_10191.jpg
raccoon_10192.jpg
raccoon_10193.jpg
raccoon_10194.jpg
raccoon_10195.jpg
raccoon_10196.jpg
raccoon_10197.jpg
raccoon_10198.jpg
raccoon_10199.jpg
raccoon_10200.jpg
(200, 4096)
rat_10001.jpg
rat_10002.jpg
rat_10003.jpg
rat_10004.jpg
rat_10005.jpg
rat_10006.jpg
rat_

rhinoceros_10182.jpg
rhinoceros_10183.jpg
rhinoceros_10184.jpg
rhinoceros_10185.jpg
rhinoceros_10186.jpg
rhinoceros_10187.jpg
rhinoceros_10188.jpg
rhinoceros_10189.jpg
rhinoceros_10190.jpg
rhinoceros_10191.jpg
rhinoceros_10192.jpg
rhinoceros_10193.jpg
rhinoceros_10194.jpg
rhinoceros_10195.jpg
rhinoceros_10196.jpg
rhinoceros_10197.jpg
rhinoceros_10198.jpg
rhinoceros_10199.jpg
rhinoceros_10200.jpg
(200, 4096)
seal_10001.jpg
seal_10002.jpg
seal_10003.jpg
seal_10004.jpg
seal_10005.jpg
seal_10006.jpg
seal_10007.jpg
seal_10008.jpg
seal_10009.jpg
seal_10010.jpg
seal_10011.jpg
seal_10012.jpg
seal_10013.jpg
seal_10014.jpg
seal_10015.jpg
seal_10016.jpg
seal_10017.jpg
seal_10018.jpg
seal_10019.jpg
seal_10020.jpg
seal_10021.jpg
seal_10022.jpg
seal_10023.jpg
seal_10024.jpg
seal_10025.jpg
seal_10026.jpg
seal_10027.jpg
seal_10028.jpg
seal_10029.jpg
seal_10030.jpg
seal_10031.jpg
seal_10032.jpg
seal_10033.jpg
seal_10034.jpg
seal_10035.jpg
seal_10036.jpg
seal_10037.jpg
seal_10038.jpg
seal_10039.jpg
seal

sheep_10208.jpg
sheep_10209.jpg
sheep_10210.jpg
sheep_10211.jpg
sheep_10212.jpg
sheep_10213.jpg
sheep_10214.jpg
sheep_10215.jpg
sheep_10216.jpg
sheep_10217.jpg
sheep_10218.jpg
sheep_10219.jpg
sheep_10220.jpg
sheep_10221.jpg
sheep_10222.jpg
sheep_10223.jpg
sheep_10224.jpg
sheep_10225.jpg
sheep_10226.jpg
sheep_10227.jpg
sheep_10228.jpg
sheep_10229.jpg
sheep_10230.jpg
sheep_10231.jpg
sheep_10232.jpg
sheep_10233.jpg
sheep_10234.jpg
sheep_10235.jpg
sheep_10236.jpg
sheep_10237.jpg
sheep_10238.jpg
sheep_10239.jpg
sheep_10240.jpg
sheep_10241.jpg
sheep_10242.jpg
sheep_10243.jpg
sheep_10244.jpg
sheep_10245.jpg
sheep_10246.jpg
sheep_10247.jpg
sheep_10248.jpg
sheep_10249.jpg
sheep_10250.jpg
sheep_10251.jpg
sheep_10252.jpg
sheep_10253.jpg
sheep_10254.jpg
sheep_10255.jpg
sheep_10256.jpg
sheep_10257.jpg
sheep_10258.jpg
sheep_10259.jpg
sheep_10260.jpg
sheep_10261.jpg
sheep_10262.jpg
sheep_10263.jpg
sheep_10264.jpg
sheep_10265.jpg
sheep_10266.jpg
sheep_10267.jpg
sheep_10268.jpg
sheep_10269.jpg
sheep_10

skunk_10076.jpg
skunk_10077.jpg
skunk_10078.jpg
skunk_10079.jpg
skunk_10080.jpg
skunk_10081.jpg
skunk_10082.jpg
skunk_10083.jpg
skunk_10084.jpg
skunk_10085.jpg
skunk_10086.jpg
skunk_10087.jpg
skunk_10088.jpg
skunk_10089.jpg
skunk_10090.jpg
skunk_10091.jpg
skunk_10092.jpg
skunk_10093.jpg
skunk_10094.jpg
skunk_10095.jpg
skunk_10096.jpg
skunk_10097.jpg
skunk_10098.jpg
skunk_10099.jpg
skunk_10100.jpg
skunk_10101.jpg
skunk_10102.jpg
skunk_10103.jpg
skunk_10104.jpg
skunk_10105.jpg
skunk_10106.jpg
skunk_10107.jpg
skunk_10108.jpg
skunk_10109.jpg
skunk_10110.jpg
skunk_10111.jpg
skunk_10112.jpg
skunk_10113.jpg
skunk_10114.jpg
skunk_10115.jpg
skunk_10116.jpg
skunk_10117.jpg
skunk_10118.jpg
skunk_10119.jpg
skunk_10120.jpg
skunk_10121.jpg
skunk_10122.jpg
skunk_10123.jpg
skunk_10124.jpg
skunk_10125.jpg
skunk_10126.jpg
skunk_10127.jpg
skunk_10128.jpg
skunk_10129.jpg
skunk_10130.jpg
skunk_10131.jpg
skunk_10132.jpg
skunk_10133.jpg
skunk_10134.jpg
skunk_10135.jpg
skunk_10136.jpg
skunk_10137.jpg
skunk_10

squirrel_10149.jpg
squirrel_10150.jpg
squirrel_10151.jpg
squirrel_10152.jpg
squirrel_10153.jpg
squirrel_10154.jpg
squirrel_10155.jpg
squirrel_10156.jpg
squirrel_10157.jpg
squirrel_10158.jpg
squirrel_10159.jpg
squirrel_10160.jpg
squirrel_10161.jpg
squirrel_10162.jpg
squirrel_10163.jpg
squirrel_10164.jpg
squirrel_10165.jpg
squirrel_10166.jpg
squirrel_10167.jpg
squirrel_10168.jpg
squirrel_10169.jpg
squirrel_10170.jpg
squirrel_10171.jpg
squirrel_10172.jpg
squirrel_10173.jpg
squirrel_10174.jpg
squirrel_10175.jpg
squirrel_10176.jpg
squirrel_10177.jpg
squirrel_10178.jpg
squirrel_10179.jpg
squirrel_10180.jpg
squirrel_10181.jpg
squirrel_10182.jpg
squirrel_10183.jpg
squirrel_10184.jpg
squirrel_10185.jpg
squirrel_10186.jpg
squirrel_10187.jpg
squirrel_10188.jpg
squirrel_10189.jpg
squirrel_10190.jpg
squirrel_10191.jpg
squirrel_10192.jpg
squirrel_10193.jpg
squirrel_10194.jpg
squirrel_10195.jpg
squirrel_10196.jpg
squirrel_10197.jpg
squirrel_10198.jpg
squirrel_10199.jpg
squirrel_10200.jpg
squirrel_102

walrus_10183.jpg
walrus_10184.jpg
walrus_10185.jpg
walrus_10186.jpg
walrus_10187.jpg
walrus_10188.jpg
walrus_10189.jpg
walrus_10190.jpg
walrus_10191.jpg
walrus_10192.jpg
walrus_10193.jpg
walrus_10194.jpg
walrus_10195.jpg
walrus_10196.jpg
walrus_10197.jpg
walrus_10198.jpg
walrus_10199.jpg
walrus_10200.jpg
walrus_10201.jpg
walrus_10202.jpg
walrus_10203.jpg
walrus_10204.jpg
walrus_10205.jpg
walrus_10206.jpg
walrus_10207.jpg
walrus_10208.jpg
walrus_10209.jpg
walrus_10210.jpg
walrus_10211.jpg
walrus_10212.jpg
walrus_10213.jpg
walrus_10214.jpg
walrus_10215.jpg
(215, 4096)
weasel_10001.jpg
weasel_10002.jpg
weasel_10003.jpg
weasel_10004.jpg
weasel_10005.jpg
weasel_10006.jpg
weasel_10007.jpg
weasel_10008.jpg
weasel_10009.jpg
weasel_10010.jpg
weasel_10011.jpg
weasel_10012.jpg
weasel_10013.jpg
weasel_10014.jpg
weasel_10015.jpg
weasel_10016.jpg
weasel_10017.jpg
weasel_10018.jpg
weasel_10019.jpg
weasel_10020.jpg
weasel_10021.jpg
weasel_10022.jpg
weasel_10023.jpg
weasel_10024.jpg
weasel_10025.jpg
we

wolf_10200.jpg
(200, 4096)
zebra_10001.jpg
zebra_10002.jpg
zebra_10003.jpg
zebra_10004.jpg
zebra_10005.jpg
zebra_10006.jpg
zebra_10007.jpg
zebra_10008.jpg
zebra_10009.jpg
zebra_10010.jpg
zebra_10011.jpg
zebra_10012.jpg
zebra_10013.jpg
zebra_10014.jpg
zebra_10015.jpg
zebra_10016.jpg
zebra_10017.jpg
zebra_10018.jpg
zebra_10019.jpg
zebra_10020.jpg
zebra_10021.jpg
zebra_10022.jpg
zebra_10023.jpg
zebra_10024.jpg
zebra_10025.jpg
zebra_10026.jpg
zebra_10027.jpg
zebra_10028.jpg
zebra_10029.jpg
zebra_10030.jpg
zebra_10031.jpg
zebra_10032.jpg
zebra_10033.jpg
zebra_10034.jpg
zebra_10035.jpg
zebra_10036.jpg
zebra_10037.jpg
zebra_10038.jpg
zebra_10039.jpg
zebra_10040.jpg
zebra_10041.jpg
zebra_10042.jpg
zebra_10043.jpg
zebra_10044.jpg
zebra_10045.jpg
zebra_10046.jpg
zebra_10047.jpg
zebra_10048.jpg
zebra_10049.jpg
zebra_10050.jpg
zebra_10051.jpg
zebra_10052.jpg
zebra_10053.jpg
zebra_10054.jpg
zebra_10055.jpg
zebra_10056.jpg
zebra_10057.jpg
zebra_10058.jpg
zebra_10059.jpg
zebra_10060.jpg
zebra_10061.j

In [12]:
#loading in the necessary data
attvect = numpy.loadtxt('predicate-matrix-binary.txt')
classes = list(numpy.loadtxt('classes.txt', delimiter='\t', usecols=[1], dtype=numpy.str))
trainlist = list(numpy.loadtxt('trainclasses.txt', delimiter='\n', dtype=numpy.str))
testlist = list(numpy.loadtxt('testclasses.txt', delimiter='\n', dtype=numpy.str))

In [13]:
'''
In this cell I create two vectors to store the predicate vectors 
for the training and testing classes, respectively.
'''
print(trainlist)

print("-"*120)

train_encs = numpy.array([attvect[classes.index(c), :] for c in trainlist])
print(train_encs)

print("-"*120)

print(testlist)

print("-"*120)

test_encs = numpy.array([attvect[classes.index(c),:] for c in testlist])
print(test_encs)


['antelope', 'grizzly+bear', 'killer+whale', 'beaver', 'dalmatian', 'horse', 'german+shepherd', 'blue+whale', 'siamese+cat', 'skunk', 'mole', 'tiger', 'moose', 'spider+monkey', 'elephant', 'gorilla', 'ox', 'fox', 'sheep', 'hamster', 'squirrel', 'rhinoceros', 'rabbit', 'bat', 'giraffe', 'wolf', 'chihuahua', 'weasel', 'otter', 'buffalo', 'zebra', 'deer', 'bobcat', 'lion', 'mouse', 'polar+bear', 'collie', 'walrus', 'cow', 'dolphin']
------------------------------------------------------------------------------------------------------------------------
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [1. 1. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 1.]]
------------------------------------------------------------------------------------------------------------------------
['chimpanzee', 'giant+panda', 'leopard', 'persian+cat', 'pig', 'hippopotamus', 'humpback+whale', 'raccoon', 'rat', 'seal']
---------------------------------------------

In [14]:
#in this function I create the input matrix in the appropriate format and the entry list which will be used in ydatagen
def xdatagen(categlist):
    X = list()
    entrylist = list()
    for folder in categlist:
        currdir = os.path.join(imfold,folder)
        #load extracted features
        ext = numpy.loadtxt(os.path.join(currdir, "extracted.txt"))
        #getting number of entries and appending to list to use in y data matrix population
        entries = ext.shape[0]
        entrylist.append(entries)

        for ind in range(entries):
            X.append(ext[ind,:])
        #print("entered "+str(entries)+" from folder "+folder) // this was used to monitor the creation of the data
    return X, entrylist

In [15]:
#creating the training input data in the appropriate format
Xtrain, trainentries = xdatagen(trainlist)
print(len(Xtrain))
print(trainentries)

11864
[250, 200, 150, 100, 250, 300, 200, 174, 250, 188, 100, 200, 300, 150, 200, 250, 300, 350, 300, 300, 250, 200, 300, 200, 300, 200, 350, 272, 350, 400, 500, 500, 630, 500, 185, 500, 500, 215, 500, 500]


In [16]:
#creating the testing input data in the appropriate format
Xtest, testentries = xdatagen(testlist)
print(len(Xtest))
print(testentries)

2450
[200, 250, 200, 200, 250, 300, 300, 200, 250, 300]


In [17]:
#here I use the entrylist with the appropriate class list to format the y data appropriately
def ydatagen(categlist, entrylist):
    ymat = list()
    for i, entries in enumerate(entrylist):
        for cnt in range(entries):
            ymat.append(attvect[classes.index(categlist[i]),:])
    return numpy.array(ymat)

In [18]:
#in this cell, the y data for training and testing are created 
ytrain = ydatagen(trainlist, trainentries)
print(len(ytrain))
print(ytrain)
ytest = ydatagen(testlist, testentries)
print(len(ytest))
print(ytest)

11864
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 1.]]
2450
[[1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]
 ...
 [1. 1. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]]


In [19]:
#here I'll create and train the attribute prediction models
def trainSVC(att):
    svm = LinearSVC(C=1e-5)
    clf = CalibratedClassifierCV(svm)
    clf.fit(Xtrain, ytrain[:, att])
    print("accuracy measured to be: {}".format(clf.score(Xtest, ytest[:, att])))
    return clf 

def train_attribute_models(func):
    clflist = []
    for i in range(attvect.shape[1]):
        print("Starting Support Vector Classifier training on classifier #{}".format(i+1))
        clflist.append(func(i))
    return clflist
clflist = train_attribute_models(trainSVC)

Starting Support Vector Classifier training on classifier #1
accuracy measured to be: 0.6383673469387755
Starting Support Vector Classifier training on classifier #2
accuracy measured to be: 0.6048979591836735
Starting Support Vector Classifier training on classifier #3
accuracy measured to be: 0.8902040816326531
Starting Support Vector Classifier training on classifier #4
accuracy measured to be: 0.5551020408163265
Starting Support Vector Classifier training on classifier #5
accuracy measured to be: 0.6751020408163265
Starting Support Vector Classifier training on classifier #6
accuracy measured to be: 0.9338775510204081
Starting Support Vector Classifier training on classifier #7
accuracy measured to be: 1.0
Starting Support Vector Classifier training on classifier #8
accuracy measured to be: 0.9640816326530612
Starting Support Vector Classifier training on classifier #9
accuracy measured to be: 0.6257142857142857
Starting Support Vector Classifier training on classifier #10
accuracy

accuracy measured to be: 0.5220408163265307
Starting Support Vector Classifier training on classifier #80
accuracy measured to be: 0.6963265306122449
Starting Support Vector Classifier training on classifier #81
accuracy measured to be: 0.8151020408163265
Starting Support Vector Classifier training on classifier #82
accuracy measured to be: 0.5857142857142857
Starting Support Vector Classifier training on classifier #83
accuracy measured to be: 0.6546938775510204
Starting Support Vector Classifier training on classifier #84
accuracy measured to be: 0.56
Starting Support Vector Classifier training on classifier #85
accuracy measured to be: 0.54


In [20]:
#saving the classifiers to a pickle file to skip training for easier work throughout the days of development
pickle_out = open("RFCs.pickle","wb")
pickle.dump(clflist, pickle_out)
pickle_out.close()

In [21]:
#loading said models
pickle_in = open("RFCs.pickle", "rb")
clflist = pickle.load(pickle_in)

In [22]:
'''
In this function I diverged from the instructions slightly and return the probabilities for 0 and for 1
since the class probability calculation example used both the probability of an attribute existing i.e. P(att=1|x) 
and not existing P(att=0|x) so both probabilities will be useful in the next part.
Of course if only the probabilities of the attribute existing are needed we can use 
probslist = []
for ext in X[test]:
    probslist.append(compute_attribute_probs(ext)[:,1])
return probslist
    
'''
#getting the probabilities for every attribute of a vector
def compute_attribute_probs(ext):
    return numpy.array([clflist[i].predict_proba([ext])[0] for i in range(attvect.shape[1])])

proba_vect = compute_attribute_probs(Xtest[0])
print(proba_vect.shape)
print(proba_vect)



(85, 2)
[[4.49945184e-01 5.50054816e-01]
 [7.01995575e-01 2.98004425e-01]
 [9.97028646e-01 2.97135419e-03]
 [2.22341575e-01 7.77658425e-01]
 [5.74751930e-01 4.25248070e-01]
 [9.04912477e-01 9.50875232e-02]
 [9.99340489e-01 6.59510518e-04]
 [9.38395835e-01 6.16041654e-02]
 [7.82808213e-01 2.17191787e-01]
 [8.69829560e-01 1.30170440e-01]
 [9.89828278e-01 1.01717223e-02]
 [3.40681605e-02 9.65931839e-01]
 [8.94642111e-01 1.05357889e-01]
 [7.74117110e-01 2.25882890e-01]
 [6.00425119e-01 3.99574881e-01]
 [1.01704516e-01 8.98295484e-01]
 [7.21987295e-01 2.78012705e-01]
 [1.90191553e-01 8.09808447e-01]
 [9.62666795e-01 3.73332046e-02]
 [2.23967499e-01 7.76032501e-01]
 [9.96269159e-01 3.73084053e-03]
 [6.95970634e-01 3.04029366e-01]
 [2.41425128e-02 9.75857487e-01]
 [5.82941789e-01 4.17058211e-01]
 [9.71958871e-01 2.80411287e-02]
 [1.29677697e-01 8.70322303e-01]
 [1.17472320e-01 8.82527680e-01]
 [1.97689080e-01 8.02310920e-01]
 [8.87684236e-01 1.12315764e-01]
 [9.85517226e-01 1.44827737e-02]
 [

In [23]:
def compute_class_probs(proba_vect):
    #list with probability for each class
    problist = list()
    for i in range(test_encs.shape[0]):
        enc = test_encs[i,:]
        prob = 1
        for ind in range(enc.shape[0]):
            prob*=proba_vect[ind, int(enc[ind])]
        problist.append(prob)
    return problist        

In [24]:
#testing the function's output
prediction = compute_class_probs(proba_vect)
print(prediction)
prediction = numpy.argmax(prediction)
print(prediction)

[1.5501433831148876e-17, 8.77145914685994e-28, 1.2298210021089351e-20, 7.887931625977659e-22, 1.5144468346575801e-30, 8.215641383041391e-32, 9.730180887674729e-46, 1.3904077386530884e-21, 1.0563541983910167e-21, 2.969621636282656e-31]
0


In [25]:
#computing the average accuracy of prediction
def compute_accuracy():
    count = 0
    for i in range(len(ytest)):
        probavect = compute_attribute_probs(Xtest[i])
        probs = compute_class_probs(probavect)
        prediction = numpy.argmax(probs)
        if numpy.array_equal(ytest[i], test_encs[prediction]):
            count+=1
    return float(count)/ len(ytest)
print("Final accuracy is: {}%".format(round(compute_accuracy()*100, 3)))

Final accuracy is: 49.143%
